# Site settings
title: Matthew Higgins | Web Developer
email: matthew.alan.higgins@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Matthew Higgins is a web developer currently located in the Los Angeles area. Since 2014 he has worked primarily as a front end developer,
  but he also has experience as a full stack Rails developer.
footer_info: > # this means to ignore newlines until "baseurl:"
  Web developer in Southern California
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.matthewalanhiggins.com" # the base hostname & protocol for your site
github_username:  mh120888
linkedin: https://www.linkedin.com/in/matthewalanhiggins⁄

# Build settings
markdown: kramdown
